### ISSUE TITLE
Add a rustfmt configuration

### ISSUE THREAD

**Issue by r3dArch** [angrynode/hightorrent#1]
Hello, I'm looking into creating a torrent client and your library seems very promising. I hope to contribute some time in the future, so I think it would be good to add a config for rustfmt to ensure good style from contributors. Thank you.

**Comment by angrynode** [comment]
Hello, thanks for the kind words!

I don't really like the default output of rustfmt (everything on several lines), but for the sake of normalization i agree with you. I added an empty rustfmt config ([9ba41ae](https://github.com/angrynode/hightorrent/commit/9ba41aefb037155232b743f7bb3c674660afd42d)). Feel free to make suggestions to improve the style.

And let me know if there's anything this crate can do to help you make writing your torrent client easier. I've just put in the features i needed myself, but there's a lot of possible improvements! (PRs and suggestions welcome)

PS: feel free to close issue if you don't have style suggestions and are happy with default rustfmt config

**Comment by r3dArch** [comment]
If you want to keep things on the same line you can try increasing the [max_width](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#max_width) in the rustfmt config. Also, would you mind telling me what you are using this crate for?

**Comment by angrynode** [comment]
> If you want to keep things on the same line you can try increasing the [max_width](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#max_width) in the rustfmt config.

Thanks for the idea!

> Also, would you mind telling me what you are using this crate for?

For two things:

- a QBittorrent API client to manage downloads
- a torrent manager with an upload form (for magnet link or torrent file): TLDR collections (with quality assurance tasks associated such as finding translations), management of symlinks in shared directory (so we don't affect torrent structure), and hopefully in the future federation via RSS or ActivityPub to follow other instances

The QBittorrent API client i'm currently polishing for publishing (along with a new hightorrent_api crate to support more clients with the same API). The TorrentManager is not really ready for publishing i still have a lot of implementation and polishing to do :)

**Comment by r3dArch** [comment]
Thank you for the response. I'll hopefully have time to work on my project soon, so I will probably have some suggestions and PRs for your crate. I wish you the best with your projects.
