### ISSUE TITLE
Magnet link without `dn` isn't parsed

### ISSUE THREAD

**Issue by fertkir** [angrynode/hightorrent#2]
Here the magnet parser requires `dn`:
https://github.com/angrynode/hightorrent/blob/main/src/magnet.rs#L131

But my link doesn't contain it, e.g.: `magnet:?xt=urn:btih:hash&tr=tracker`

**Comment by fertkir** [comment]
A proposed fix: https://github.com/angrynode/hightorrent/pull/3

**Comment by angrynode** [comment]
Hello, thanks for your PR. This is now supported and tested. Feel free to reopen the issue in the future if something doesn't work as expected.
